# Generated by Django 5.0.3 on 2024-03-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catpost',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='catpost',
            name='author_name',
        ),
        migrations.AddField(
            model_name='catpost',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catpost',
            name='image',
            field=models.ImageField(max_length=20, upload_to='cats_app/static/cat_photos/'),
        ),
    ]
